
#ifndef IMAGECALIBRATIONLIB_EXPORT_H
#define IMAGECALIBRATIONLIB_EXPORT_H

#ifdef IMAGECALIBRATIONLIB_STATIC_DEFINE
#  define IMAGECALIBRATIONLIB_EXPORT
#  define IMAGECALIBRATIONLIB_NO_EXPORT
#else
#  ifndef IMAGECALIBRATIONLIB_EXPORT
#    ifdef ImageCalibrationLib_EXPORTS
        /* We are building this library */
#      define IMAGECALIBRATIONLIB_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define IMAGECALIBRATIONLIB_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef IMAGECALIBRATIONLIB_NO_EXPORT
#    define IMAGECALIBRATIONLIB_NO_EXPORT 
#  endif
#endif

#ifndef IMAGECALIBRATIONLIB_DEPRECATED
#  define IMAGECALIBRATIONLIB_DEPRECATED __declspec(deprecated)
#endif

#ifndef IMAGECALIBRATIONLIB_DEPRECATED_EXPORT
#  define IMAGECALIBRATIONLIB_DEPRECATED_EXPORT IMAGECALIBRATIONLIB_EXPORT IMAGECALIBRATIONLIB_DEPRECATED
#endif

#ifndef IMAGECALIBRATIONLIB_DEPRECATED_NO_EXPORT
#  define IMAGECALIBRATIONLIB_DEPRECATED_NO_EXPORT IMAGECALIBRATIONLIB_NO_EXPORT IMAGECALIBRATIONLIB_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef IMAGECALIBRATIONLIB_NO_DEPRECATED
#    define IMAGECALIBRATIONLIB_NO_DEPRECATED
#  endif
#endif

#endif /* IMAGECALIBRATIONLIB_EXPORT_H */
